[package]
name = "quantum-game"
version = "0.1.0"
edition = "2021"

license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15"
num-complex = "0.4"
rand = "0.8"
num = "0.4"
